global:
  resolve_timeout: 5m

  smtp_smarthost: 'smtp.qq.com:587'
  smtp_from: '3356028829@qq.com'
  smtp_auth_username: '3356028829@qq.com'
  smtp_auth_password: 'jldqnwmjdudycifi'
  smtp_require_tls: true

route:
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: '3356028829@qq.com'
        send_resolved: true
